### ISSUE TITLE
Identify loops in graph structure

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/DE-learning#67]
Positive feedback loops are a way of creating "memory", where a cell's molecular state is sustained. I think it will help to better understand the upstream regulators if we identify these loops. It looks like NetworkX has [a method to identify loops](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.find_cycle.html), then positive feedback would be loops where the product of the edge weights are positive.

**Comment by Zhanzhang-2020** [comment]
It seems that the method can only return one loop?

**Comment by Zhanzhang-2020** [comment]
Another method nx.simple_cycles(G) can return all the loop, but do not provide the detailed path in the loop

**Comment by Zhanzhang-2020** [comment]
I think I have figured it out

**Comment by Zhanzhang-2020** [comment]
I have written a loop() function to find all possible positive feedback loop. However, there seems no loop except the self-interacting loops under the current threshold for edge weights, so I lowered the threshold. Also, since the NetworkX method could only return one loop each time, I have to remove one edge of the loop in order to destroy the loop before moving on to find the next loop. This could be an issue because some loops share the same edge, and I haven't figured out how to solve this problem.

**Comment by aarmey** [comment]
I think the way the w matrix is thresholded isn't quite right (see other issue), so agree with lowering the threshold. For the other issue, maybe look here? https://gist.github.com/joe-jordan/6548029

**Comment by Zhanzhang-2020** [comment]
The function seems only work for undirected graph

**Comment by Zhanzhang-2020** [comment]
I just realized that the loop that nx.simple_cycles(G) returned has been sorted according to the path, so it meets our purpose.
